services:
#  Our PostgreSQL db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: shalini@06

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080